version: "3.8"

services:
  geofences:
    build:
      context: .
      dockerfile: Dockerfile
    image: geofences
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/geofences
      - SPRING_DATASOURCE_USERNAME=geofences
      - SPRING_DATASOURCE_PASSWORD=geofences
    depends_on:
      - db
    ports:
      - 8080:8080
  db:
    image: postgres:14.2
    environment:
      - POSTGRES_USER=geofences
      - POSTGRES_PASSWORD=geofences
    ports:
      - 5432:5432
